# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ikDcOBgx0UWKC2y3bhPCrk6bFysN13Xy
"""

import pandas as pd
import random

class DutyScheduler:
    def __init__(self, teachers_df, timetable_df, locations_df):
        self.teachers = self._process_teachers(teachers_df)
        self.timetable = self._process_timetable(timetable_df)
        self.locations = self._process_locations(locations_df)
        self.duties = self._define_duties()
        self.schedule = {duty: [] for duty in self.duties}
        self.target_scores = {'副校': 8, '主任': 8, '班主任': 6, '非班主任': 6}

    def _process_teachers(self, df):
        teachers_dict = {}
        for _, row in df.iterrows():
            teachers_dict[row['name']] = {
                'role': row['role'],
                'is_pe': str(row['is_pe_teacher']).strip() == '是',
                'special_role': row.get('special_role', '無'),
                'score': 0,
                'duties_count': 0
            }
        return teachers_dict

    def _process_timetable(self, df):
        tt = {}
        for name in self.teachers:
            tt[name] = {}
            for day in ['星期一', '星期二', '星期三', '星期四', '星期五']:
                tt[name][day] = list(df[(df['teacher_name'] == name) & (df['day'] == day)]['period'].values)
        return tt

    def _process_locations(self, df):
        loc = {}
        # Simple processing for demonstration
        return df.set_index(['teacher_name', 'day', 'period'])['floor'].to_dict()


    def _define_duties(self):
        duties = {}
        days = ['星期一', '星期二', '星期三', '星期四', '星期五']

        # Morning Duties (VP/HoD)
        for day in days:
            duties[f'{day}_早上_大閘_1'] = {'weight': 1, 'time_slot': (7, 30, 7, 45), 'roles': ['副校', '主任'], 'headcount': 1}
            duties[f'{day}_早上_大閘_2'] = {'weight': 1, 'time_slot': (7, 45, 8, 0), 'roles': ['副校', '主任'], 'headcount': 1}
            duties[f'{day}_早上_大閘_3'] = {'weight': 1, 'time_slot': (8, 0, 8, 15), 'roles': ['副校', '主任'], 'headcount': 1}
            duties[f'{day}_早上_舊翼操場_1'] = {'weight': 1, 'time_slot': (7, 30, 7, 45), 'roles': ['副校', '主任'], 'headcount': 1}
            duties[f'{day}_早上_舊翼操場_2'] = {'weight': 1, 'time_slot': (7, 45, 8, 0), 'roles': ['副校', '主任'], 'headcount': 2} # Increased headcount
            duties[f'{day}_早上_玻璃門_1'] = {'weight': 1, 'time_slot': (7, 30, 7, 45), 'roles': ['副校', '主任'], 'headcount': 1}
            duties[f'{day}_早上_玻璃門_2'] = {'weight': 1, 'time_slot': (7, 45, 8, 0), 'roles': ['副校', '主任'], 'headcount': 1}
            duties[f'{day}_早上_玻璃門_3'] = {'weight': 1, 'time_slot': (8, 0, 8, 15), 'roles': ['副校', '主任'], 'headcount': 1}

        # Recess Duties (Class/Non-Class Teacher)
        recess_times = ['小息一', '小息二']
        for day in days:
            for recess in recess_times:
                duties[f'{day}_{recess}_地下'] = {'weight': 1, 'roles': ['班主任', '非班主任'], 'headcount': 3, 'pe_required': True}
                for floor in ['1', '2', '4', '5', '6']:
                    duties[f'{day}_{recess}_樓層{floor}'] = {'weight': 1, 'roles': ['班主任', '非班主任'], 'headcount': 2}
                duties[f'{day}_{recess}_樓層3'] = {'weight': 1, 'roles': ['班主任', '非班主任'], 'headcount': 1}

        # Lunch Duties (VP/HoD/Non-Class Teacher)
        for day in days:
            duties[f'{day}_午膳二_地下'] = {'weight': 2, 'roles': ['副校', '主任', '非班主任'], 'headcount': 2}
            for floor in ['1', '2', '4', '5', '6']:
                duties[f'{day}_午膳二_樓層{floor}'] = {'weight': 2, 'roles': ['副校', '主任', '非班主任'], 'headcount': 2}
            duties[f'{day}_午膳二_樓層3'] = {'weight': 2, 'roles': ['副校', '主任', '非班主任'], 'headcount': 1}

        # After School Duties
        for day in days:
            # On-site duties (VP/HoD)
            for post in ['操場持咪', '新翼持咪', '家長隊', '大閘', '校門']:
                 duties[f'{day}_放學當值_{post}'] = {'weight': 1, 'roles': ['副校', '主任'], 'headcount': 1}
            # Team leading (Class/Non-Class Teacher)
            for route in ['火車站A', '火車站B', '欣盛', '華明', '景盛牽晴間', '碧湖粉嶺中心']:
                duties[f'{day}_放學帶隊_{route}'] = {'weight': 1, 'roles': ['班主任', '非班主任'], 'headcount': 1}

        return duties

    def check_availability(self, teacher_name, day, period):
        # This is a simplified check. A real implementation would need to parse lesson times.
        if day in self.timetable[teacher_name] and period in self.timetable[teacher_name][day]:
            return False
        # Check for 6 consecutive lessons
        lessons_today = sorted(self.timetable[teacher_name].get(day, []))
        if len(lessons_today) >= 6:
            for i in range(len(lessons_today) - 5):
                if all(lessons_today[i+j] == lessons_today[i]+j for j in range(6)):
                     print(f"     - [人性化檢查] {teacher_name} 該天有六連堂，跳過。")
                     return False
        return True

    def run_scheduler(self, week_type):
        print(f"\n--- 正在為【{week_type}】進行排表 ---\n")
        # Reset scores for each run
        for name in self.teachers:
            self.teachers[name]['score'] = 0

        # Handle fixed duties first
        self.schedule['星期一_早上_大閘_1'] = ['陳淑怡'] # Example fixed duty
        self.teachers['陳淑怡']['score'] += self.duties['星期一_早上_大閘_1']['weight']

        # A more robust system would abstract this.
        # This is a simplified greedy algorithm
        for duty_name, details in self.duties.items():
            if self.schedule.get(duty_name): # Skip if already filled (e.g., fixed duties)
                continue

            print(f"正在安排: {duty_name} (需要 {details['headcount']} 人)")

            # --- Candidate Selection ---
            candidates = []
            for name, teacher_info in self.teachers.items():
                # 1. Role check
                if teacher_info['role'] not in details['roles']:
                    continue
                # 2. Availability Check (Simplified - needs real time mapping)
                # This is a placeholder for a much more complex availability check
                is_available = True
                if not self.check_availability(name, duty_name.split('_')[0], 3): # Period 3 for demo
                    is_available = False

                # 3. Special Role Constraints
                if teacher_info.get('special_role') == '輔導主任' and ('小息' in duty_name or '午膳' in duty_name):
                    continue
                if teacher_info.get('special_role') == '圖書館老師' and '放學帶隊' not in duty_name:
                    continue

                if is_available:
                    candidates.append(name)

            # --- Assignment ---
            assigned_teachers = []
            # Sort by score to ensure fairness
            candidates.sort(key=lambda n: self.teachers[n]['score'])

            # Handle PE teacher requirement
            if details.get('pe_required'):
                pe_teacher = next((p for p in candidates if self.teachers[p]['is_pe']), None)
                if pe_teacher:
                    assigned_teachers.append(pe_teacher)
                    candidates.remove(pe_teacher)

            # Fill remaining spots
            needed = details['headcount'] - len(assigned_teachers)
            if len(candidates) >= needed:
                assigned_teachers.extend(candidates[:needed])
            else:
                 assigned_teachers.extend(candidates)
                 print(f"     - [警告] {duty_name} 人手不足! 只找到 {len(assigned_teachers)}/{details['headcount']} 人。")

            # Update schedule and scores
            self.schedule[duty_name] = assigned_teachers
            for teacher in assigned_teachers:
                self.teachers[teacher]['score'] += details['weight']

        return self.schedule, self.teachers

# --- Main Execution ---
try:
    # In a real environment, you'd upload these files.
    # Here, we assume they are in the current directory.
    print("正在讀取上傳的 CSV 檔案...")
    df_teachers = pd.read_csv('teachers_list.csv')
    df_timetable = pd.read_csv('timetable.csv')
    df_locations = pd.read_csv('class_locations.csv')
    print("✅ 檔案讀取成功！")

    scheduler = DutyScheduler(df_teachers, df_timetable, df_locations)

    # --- Run for ODD week ---
    odd_week_schedule, odd_week_scores = scheduler.run_scheduler("單數週")

    print("\n\n" + "="*40)
    print("          📅 單數週 當值表 (初稿)          ")
    print("="*40)
    for duty, staff in odd_week_schedule.items():
        if staff: # Only print duties that have been assigned
            print(f"- {duty:<30}: {', '.join(staff)}")

    print("\n\n" + "="*40)
    print("          📊 單數週 老師工作量統計          ")
    print("="*40)
    for name, info in odd_week_scores.items():
        print(f"- {name:<5} ({info['role']:<4}): {info['score']} 分")

    # In a full implementation, you would run for a double week with different rules
    # scheduler.run_scheduler("雙數週")

except FileNotFoundError as e:
    print(f"\n❌ 錯誤：找不到必要的檔案 -> {e.filename}")
    print("請確認您已經上傳了 `teachers_list.csv`, `timetable.csv`, 和 `class_locations.csv` 並且檔名完全正確。")
except Exception as e:
    print(f"\n❌ 發生未預期的錯誤: {e}")
    print("請檢查您的 CSV 檔案格式是否與範本一致。")